import os

from config.files_config import data_path

DEBUG_PURGE_DATA = False
DEBUG_SHARE_BUNDLE = True
DEBUG_ADD_PEERS = True
DEBUG_REMOVE_PREV_PEERS = True
DEBUG_ADD_GROUPS = True
DEBUG_DISABLE_ENCRYPTION = True
DEBUG_DISABLE_DISK_REQUESTS = False
DEBUG_DISABLE_UPLOAD_MEDIA_DATA = True
DEBUG_DISABLE_COMMUNICATION = True
DEBUG_DISABLE_PEER_REQUESTS = False
DEBUG_RESOLVE_REQUESTS_SEQUENTIALLY = False

peer_addr_dir = os.path.join(data_path, "peers")
